mr-manuel_arp-ndp-logging: {
  url: "https://mr-manuel.github.io/opnsense_arp-ndp-logging/",
  enabled: yes,
  signature_type: "pubkey",
  pubkey: "/usr/local/etc/pkg/repos/mr-manuel_arp-ndp-logging.pub",
  priority: 0
}
